// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	BooksAPIService := openapi.NewBooksAPIService()
	BooksAPIController := openapi.NewBooksAPIController(BooksAPIService)

	router := openapi.NewRouter(BooksAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
