// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi




type Metadata struct {

	Total int32 `json:"total,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	Offset int32 `json:"offset,omitempty"`
}

// AssertMetadataRequired checks if the required fields are not zero-ed
func AssertMetadataRequired(obj Metadata) error {
	return nil
}

// AssertMetadataConstraints checks if the values respects the defined constraints
func AssertMetadataConstraints(obj Metadata) error {
	return nil
}
