openapi: 3.1.0
info:
  title: Inkspire
  description: |
    This app allows for making lists of various types across different media and will eventually have
    fuzzy searching and rating functionality added to it.
  version: 0.0.1
paths:
  /books:
    get:
      summary: Get all books
      description: Get all books from the list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - title
                  - author
                properties:
                  id:
                    type: integer
                    format: int32
                  title:
                    type: string
                    minLength: 1
                    maxLength: 50
                  author:
                    type: string
                    minLength: 1
                    maxLength: 50
  /books/{id}:
    get:
      summary: Get a specific book
      description: Get a specific book by passing its id and return the book info
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1

    post:
      summary:
      description:
      parameters:
      responses:
    delete:

  /anime:
