openapi: 3.1.0
info:
  title: Inkspire
  description: |
    This app allows for making lists of various types across different media and will eventually have
    fuzzy searching and rating functionality added to it.
  version: 0.0.1
paths:
  /books:
    get:
      summary: Get all books
      description: Get all books from the list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
    post:
      summary: Add a book
      description: Add a specific book
      requestBody:
        description: Create a new book
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "400":
          description: Invalid input
  /books/{bookId}:
    get:
      summary: Get a specific book
      description: Get a specific book by passing its bookId and return the book info
      parameters:
        - $ref: "#/components/parameters/BookId"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "400":
          description: Invalid input or missing bookId
    delete:
      summary: Delete a book
      description: Delete a specific book by bookId
      parameters:
        - $ref: "#/components/parameters/BookId"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "400":
          description: Invalid input or missing bookId
components:
  schemas:
    Book:
      required:
        - id
        - name
        - author
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: The Lusty Argonian Maid
        author:
          type: string
          example: Sandon Branderson
        series:
          type: string
          example: Wheel of Time
        genre:
          type: array
          items:
            type: string
            example: ["Fantasy", "Epic", "Thriller"]
        pages:
          type: integer
          example: 1690
      type: object
  parameters:
    BookId:
      name: bookId
      in: path
      required: true
      description: The ID of the book.
      schema:
        type: integer
        format: int32
  /anime:
