openapi: 3.1.0
info:
  title: Inkspire
  description: |
    This app allows for making lists of various types across different media and will eventually have
    fuzzy searching and rating functionality added to it.
  version: 0.0.1
tags:
  - name: Books
    description: Track read and to-be-read books
paths:
  /books:
    $ref: "paths/books.yaml"
  /books/{bookId}:
    $ref: "paths/book.yaml"
components:
  responses:
    $ref: "components/responses/_index.yaml"
  parameters:
    $ref: "components/parameters/_index.yaml"
  schemas:
    $ref: "components/schemas/_index.yaml"
  headers:
    $ref: "components/headers/_index.yaml"
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server
