// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi




type Problem struct {

	// A URI reference that identifies the problem type.
	Type string `json:"type,omitempty"`

	// A short, human-readable summary of the problem type.
	Title string `json:"title,omitempty"`

	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`

	// A URI reference that identifies the specific occurrence of the problem.
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	Status int32 `json:"status,omitempty"`
}

// AssertProblemRequired checks if the required fields are not zero-ed
func AssertProblemRequired(obj Problem) error {
	return nil
}

// AssertProblemConstraints checks if the values respects the defined constraints
func AssertProblemConstraints(obj Problem) error {
	return nil
}
