// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi




type Series struct {

	Id string `json:"id"`

	Name string `json:"name"`
}

// AssertSeriesRequired checks if the required fields are not zero-ed
func AssertSeriesRequired(obj Series) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSeriesConstraints checks if the values respects the defined constraints
func AssertSeriesConstraints(obj Series) error {
	return nil
}
