// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi




type CreatedResponse struct {

	// The unique identifier of the created resource.
	Id string `json:"id,omitempty"`

	// Confirmation message.
	Message string `json:"message,omitempty"`
}

// AssertCreatedResponseRequired checks if the required fields are not zero-ed
func AssertCreatedResponseRequired(obj CreatedResponse) error {
	return nil
}

// AssertCreatedResponseConstraints checks if the values respects the defined constraints
func AssertCreatedResponseConstraints(obj CreatedResponse) error {
	return nil
}
