/*
Inkspire

This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedResponse{}

// CreatedResponse struct for CreatedResponse
type CreatedResponse struct {
	// The unique identifier of the created resource.
	Id *string `json:"id,omitempty"`
	// Confirmation message.
	Message *string `json:"message,omitempty"`
}

// NewCreatedResponse instantiates a new CreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedResponse() *CreatedResponse {
	this := CreatedResponse{}
	return &this
}

// NewCreatedResponseWithDefaults instantiates a new CreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedResponseWithDefaults() *CreatedResponse {
	this := CreatedResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreatedResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreatedResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreatedResponse) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreatedResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatedResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreatedResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreatedResponse) SetMessage(v string) {
	o.Message = &v
}

func (o CreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreatedResponse struct {
	value *CreatedResponse
	isSet bool
}

func (v NullableCreatedResponse) Get() *CreatedResponse {
	return v.value
}

func (v *NullableCreatedResponse) Set(val *CreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedResponse(val *CreatedResponse) *NullableCreatedResponse {
	return &NullableCreatedResponse{value: val, isSet: true}
}

func (v NullableCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


