// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi

import (
	"context"
	"net/http"
	"reflect"
)



// BooksAPIRouter defines the required methods for binding the api requests to a responses for the BooksAPI
// The BooksAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BooksAPIServicer to perform the required actions, then write the service results to the http response.
type BooksAPIRouter interface { 
	GetBooks(http.ResponseWriter, *http.Request)
	AddBook(http.ResponseWriter, *http.Request)
	GetBook(http.ResponseWriter, *http.Request)
	ReplaceBook(http.ResponseWriter, *http.Request)
	DeleteBook(http.ResponseWriter, *http.Request)
	UpdateBook(http.ResponseWriter, *http.Request)
}


// BooksAPIServicer defines the api actions for the BooksAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BooksAPIServicer interface { 
	GetBooks(context.Context, int32, int32, []string, string, string, string) (ImplResponse, error)
	AddBook(context.Context, NewBook) (ImplResponse, error)
	GetBook(context.Context, string) (ImplResponse, error)
	ReplaceBook(context.Context, string, Book) (ImplResponse, error)
	DeleteBook(context.Context, string) (ImplResponse, error)
	UpdateBook(context.Context, string, Book) (ImplResponse, error)
}
