// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi




type GetBooks200Response struct {

	Data []Book `json:"data,omitempty"`

	Metadata Metadata `json:"metadata,omitempty"`
}

// AssertGetBooks200ResponseRequired checks if the required fields are not zero-ed
func AssertGetBooks200ResponseRequired(obj GetBooks200Response) error {
	for _, el := range obj.Data {
		if err := AssertBookRequired(el); err != nil {
			return err
		}
	}
	if err := AssertMetadataRequired(obj.Metadata); err != nil {
		return err
	}
	return nil
}

// AssertGetBooks200ResponseConstraints checks if the values respects the defined constraints
func AssertGetBooks200ResponseConstraints(obj GetBooks200Response) error {
	for _, el := range obj.Data {
		if err := AssertBookConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertMetadataConstraints(obj.Metadata); err != nil {
		return err
	}
	return nil
}
