// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Inkspire
 *
 * This app allows for making lists of various types across different media and will eventually have fuzzy searching and rating functionality added to it. 
 *
 * API version: 0.0.1
 */

package openapi


import (
	"errors"
)



type NewBook struct {

	Title string `json:"title,omitempty"`

	AuthorId string `json:"authorId,omitempty"`

	SeriesId string `json:"seriesId,omitempty"`

	Genres []string `json:"genres,omitempty"`

	Pages int32 `json:"pages,omitempty"`

	Status string `json:"status,omitempty"`
}

// AssertNewBookRequired checks if the required fields are not zero-ed
func AssertNewBookRequired(obj NewBook) error {
	return nil
}

// AssertNewBookConstraints checks if the values respects the defined constraints
func AssertNewBookConstraints(obj NewBook) error {
	if obj.Pages < 1 {
		return &ParsingError{Param: "Pages", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
